version: 0.1

environment_variables:
  plaintext:
    PYTHON_BIN_PATH: "/bin/python"
    TF_NEED_MKL: "0"
    CC_OPT_FLAGS: "-march=native"
    TF_NEED_JEMALLOC: "1"
    TF_NEED_GCP: "0"
    TF_NEED_HDFS: "0"
    TF_ENABLE_XLA: "0"
    TF_NEED_OPENCL: "0"
    TF_NEED_CUDA: "0"
    TF_BUILD_CONTAINER_TYPE: "cpu"
    TF_BUILD_IS_OPT: "OPT"
    TF_BUILD_DRY_RUN: "1"
    TF_BUILD_ENABLE_XLA: "1"
    TF_BUILD_BAZEL_TARGET: "//tensorflow/aot:tfcompile"
    TF_BUILD_OPTIONS: "FASTBUILD"
            
phases:
  build:
    commands:
      - ./tensorflow/tools/ci_builds/ci_parameterized_build.sh
      - ./tensorflow/contrib/pi_examples/aot_xla/build.sh 3
  post_build:
    commands:
      - ls ./tensorflow/contrib/pi_examples/aot_xla
artifacts:
  files:
    - /tensorflow/tensorflow/compiler/aot/tfcompile
  discard-paths: yes
  base-directory: /
